---
# tasks file for mysql_role


- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  ignore_errors: True

- name: Include Debian specific tasks
  include: Debian.yml
  when: ansible_os_family == 'Debian'
  
- name: Include RedHat specific tasks
  include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Check for Un-Supported Operating System
  fail:
    msg: "Operating System of the target machine ({{ inventory_hostname }}) is currently not supported"
  when: mysql_supported_os is not defined
  ignore_errors: True

- name: setup replication if set
  include: replication.yml
  when: mysql_replication
  ignore_errors: True